### ISSUE TITLE
icons do not load correctly

### ISSUE THREAD

**Issue by hannesdelbeke** [leixingyu/unrealStylesheet#2]
similar to https://github.com/leixingyu/unrealScriptEditor/issues/3

to fix:
```python
# change 
QtCore.QResource.registerResource("icons.rcc")
# to 
QtCore.QResource.registerResource(str(MODULE_PATH / "icons.rcc") )
```
now the rcc loads correctly, and no changes are needed to any other file. one line fix.
will create a PR for this

**Comment by hannesdelbeke** [comment]
explanation

old code
```python
QtCore.QResource.registerResource("icons.rcc") 
# this assumes this script runs from the same folder as icons.rcc
# or that icons.rcc is in the path.
# if however you import the stylesheet as a module, or anywhere not in the main path
# the icons can't be found in the search path. 
```

new code
```python
QtCore.QResource.registerResource(str(MODULE_PATH / "icons.rcc") )
# the new code sets the Resource path to an explicit path, using pathlib
str(MODULE_PATH / "icons.rcc") # is actually the same as 
"C:\Users\hanne\OneDrive\Documents\repos\unrealStylesheet\unreal_qt_stylesheet\icons.rcc"
```

also see [pyside searchpath docs](https://doc.qt.io/qtforpython-5/PySide2/QtGui/QIcon.html#PySide2.QtGui.PySide2.QtGui.QIcon.themeSearchPaths)

**Comment by leixingyu** [comment]
Can we get rid of the pathlib, seems like it's introduced in 3.4?
can we just use `os.path.join` for compatibility reasons?

**Comment by hannesdelbeke** [comment]
- removed pathlib
- PR3 is now merged in cllosing this issue
