### ISSUE TITLE
setup PyPI build pipeline on github

### ISSUE THREAD

**Issue by hannesdelbeke** [leixingyu/unrealStylesheet#6]
Now that #3  is merged in, ideally we now would setup a build pipeline on github, to release this stylesheet to PyPI when there are updates.
I'm currently releasing from [my fork](https://github.com/hannesdelbeke/unrealStylesheet).

If you want, you could make me a maintainer of this repo to help with the set up.

here are the setup steps for the release pipeline:

- [ ] #7
- [ ] Once you have project acces on pypi, you can 'add an API token' with scope `unreal_stylesheet` in your [PyPI account settings](https://pypi.org/manage/account/). 
- [ ] Then add a secret to the github repo with name PYPI_API_TOKEN, and paste the API token in there.
(optionally you can also set up a github environment named PyPI, and add the secret here instead.)

The last PR already merged in a GitHub release workflow, which after following the above steps, will automatically release to PyPI when creating a release in GitHub.
(it does require you to bump the release version in the `toml` , else the PyPI update will fail)
![image](https://github.com/leixingyu/unrealStylesheet/assets/3758308/385715ae-ce5c-46a7-b565-4ea214520507)

**Comment by leixingyu** [comment]
Hi, my account name is: xingyulei

**Comment by hannesdelbeke** [comment]
hi, I've send you an invite for pypi.
Your role has been set to owner, which enables all permissions.

**Comment by leixingyu** [comment]
thank you very much, I think I've configured everything correctly, will do a test when an update is needed

**Comment by hannesdelbeke** [comment]
there actually is 1 update that's not in the latest release, 
I haven't released the stylesheet support for disabled combobox. and left it for you, so you can test the release.

- [ ] so if you do a release it should add support for the Qcombobox, sicne it's already commited/merged in.
don't forget to bump the version to 0.0.3 [here](https://github.com/leixingyu/unrealStylesheet/blob/master/pyproject.toml) before you do

**Comment by hannesdelbeke** [comment]
and since this is on pypi, it now shows other projects that use this in the side bar under "used by" 👍 
because these projects have this repo in their toml dependencies  
![image](https://github.com/leixingyu/unrealStylesheet/assets/3758308/5f10c8a1-aae9-402e-9350-f73f3bc30af3)

**Comment by leixingyu** [comment]
This is very cool Hannes, 
I'll test this out in the next couple of weeks but I'm pretty low on bandwidth recently, so bear with me with the response time

**Comment by leixingyu** [comment]
just tested out the pypi build pipeline, very neat
